services:
  app:
    container_name: nestjs_app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: 
     - .:/app
     - pnpm-store:/pnpm/store
    depends_on:
      - db 
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      DATABASE_NAME: test_db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment: 
      MYSQL_ROOT_PASSWORD: secrert
      MYSQL_DATABASE: test_db 
    ports:
      - "3306:3306"
volumes:
  pnpm-store: